language: perl
env:
    - DEB_BUILD_OPTIONS="parallel=2"
before_install:
    - sudo apt-add-repository -y ppa:rsrchboy/ndn-perl
    - sudo apt-get update -q > /dev/null
install:
    - sudo apt-get install -q -y build-essential debhelper devscripts equivs > /dev/null
    - sudo mk-build-deps --install debian/control
script:
    - debuild -S -us -uc --lintian-opts --profile ndn
    - debuild -us -uc --lintian-opts --profile ndn
    - sudo dpkg -i ../*.deb
after_success:
    - openssl aes-256-cbc -K $encrypted_ce1d6e045b56_key -iv $encrypted_ce1d6e045b56_iv
      -in deploy_id.enc -out debian/travis/deploy_id -d
    - chmod 0600 debian/travis/deploy_id
    - ./debian/travis.after_success

