language: perl
env:
    - DEB_BUILD_OPTIONS="parallel=4"
before_install:
    - sudo apt-add-repository -y ppa:rsrchboy/ndn-perl
    - sudo apt-get update -q > /dev/null
install:
    - sudo apt-get install -q -y build-essential debhelper devscripts equivs > /dev/null
    - sudo mk-build-deps --install debian/control
script:
    - debuild -S -us -uc --lintian-opts --profile ndn
    - debuild -us -uc --lintian-opts --profile ndn
    - sudo dpkg -i ../*.deb
